#!/bin/sh

INSTALLPATH=/usr/local/lib
LINKERNAME=libtest.so
SONAME=${LINKERNAME}.1
REALNAME=${LINKERNAME}.1.0.2

cp $REALNAME $INSTALLPATH
cd $INSTALLPATH
ln -sf $REALNAME $LINKERNAME
ln -sf $REALNAME $SONAME

ls -l
